Bug #1066878 asoc: sprd: remove code build warnings for clang
[root cause  ] build error
[changes     ] suppress the warning for code logical won't be changed
[side effects]no
[self test   ]:yes
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:yes
[is there dependence]:no
[confirm dependent commit]:yes
[board]:ums512
[test case]:build by clang
[reviewers   ] peter.huang
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

Fix build errors for clang.
../sound/soc/sprd/platform/sprd-dmaengine-pcm.c:1629:31: error: shift count >= width of type [-Werror,-Wshift-count-overflow]

Change-Id: I5ff03fefd6758181836cdfaa6f9c18ed476ba4d1
Signed-off-by: Harvey Yin <harvey.yin@unisoc.com>