Bug #1066878 input: touchscreen: Remove code build warnings for clang
[root cause  ] [-Werror,-Wenum-conversion]
[changes     ] The wrong enum type used, changes it
[side effects] No
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: No
[board]: sp9863a
[test case]: build by clang
[reviewers   ] nianfu.bai
[change_type ] feature
[tag_product ] common

../drivers/input/touchscreen/adaptive-ts/vendors/ats_focaltech.c:372:22: error: implicit conversion from enumeration type 'enum ts_result' to different enumeration type 'enum ts_event' [-Werror,-Wenum-conversion]
        enum ts_event ret = TSRESULT_EVENT_HANDLED;
                      ~~~   ^~~~~~~~~~~~~~~~~~~~~~

Change-Id: Ifb44b1ad0ba61c497e18f7f979a966ff6bc30e0a
Signed-off-by: Candle Sun <candle.sun@unisoc.com>