Bug #1066878 asoc: sprd: remove code build warnings for clang
[root cause  ] [-Werror,-Wshift-count-overflow] [-Werror,-Wunused-function]
[changes     ] Suppress warnings, for code won't be changed
[side effects] No
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: No
[board]: sp9863a
[test case]: build by clang
[reviewers   ] nianfu.bai
[change_type ] feature
[tag_product ] common

Add pragmas to ignore [-Werror,-Wshift-count-overflow]
[-Werror,-Wunused-function] Werror

../sound/soc/sprd/codec/sprd/sc2721/sprd-codec.c:236:12: error: unused function '__xtlbuf1_eb_set' [-Werror,-Wunused-function]
static int __xtlbuf1_eb_set(void)
           ^
../sound/soc/sprd/codec/sprd/sc2721/sprd-codec.c:243:12: error: unused function '__xtlbuf1_eb_clr' [-Werror,-Wunused-function]
static int __xtlbuf1_eb_clr(void)
           ^
../sound/soc/sprd/codec/sprd/sc2721/sprd-codec.c:252:17: error: unused function '__sprd_get_vbat_voltage' [-Werror,-Wunused-function]
static uint32_t __sprd_get_vbat_voltage(void)
                ^
../sound/soc/sprd/codec/sprd/sc2721/sprd-codec.c:260:12: error: unused function '__agdsp_access_enable' [-Werror,-Wunused-function]
static int __agdsp_access_enable(void)
           ^
../sound/soc/sprd/codec/sprd/sc2721/sprd-codec.c:268:12: error: unused function '__agdsp_access_disable' [-Werror,-Wunused-function]
static int __agdsp_access_disable(void)
           ^
../sound/soc/sprd/codec/sprd/sc2731/sprd-headset-sc2731.c:86:12: error: unused function '__dsp_fm_mute_by_set_dg' [-Werror,-Wunused-function]
static int __dsp_fm_mute_by_set_dg(void)
           ^
../sound/soc/sprd/codec/sprd/sc2731/sprd-headset-sc2731.c:135:12: error: unused function '__vbc_close_fm_dggain' [-Werror,-Wunused-function]
static int __vbc_close_fm_dggain(bool mute)
           ^

Change-Id: I47d68f6b9ed65d442a8a5eb4ff491a9684146dfe
Signed-off-by: Candle Sun <candle.sun@unisoc.com>