camera: fix enum type in get_fetch_format() default case
Correct copy-paste error where get_fetch_format() incorrectly used
ISP_STORE_FORMAT_MAX instead of ISP_FETCH_FORMAT_MAX in default case.

../drivers/misc/sprd_camera/cam_sl5_roc1/src/isp_path.c:160:12: error: implicit conversion from enumeration type 'enum isp_store_format' to different enumeration type 'enum isp_fetch_format' [-Werror,-Wenum-conversion]
                format = ISP_STORE_FORMAT_MAX;
                       ~ ^~~~~~~~~~~~~~~~~~~~
1 error generated.